# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ronny

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Ronny The Voice Assistent")
        MainWindow.resize(1308, 822)
        MainWindow.setStyleSheet("background:transparent;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.label_Main_bg = QtWidgets.QLabel(self.centralwidget)
        self.label_Main_bg.setGeometry(QtCore.QRect(0, 0, 1311, 781))
        self.label_Main_bg.setStyleSheet("background-color: rgb(0, 0, 95);")
        self.label_Main_bg.setText("")
        self.label_Main_bg.setPixmap(QtGui.QPixmap("../guiobject/black_bg.jpg"))
        self.label_Main_bg.setScaledContents(True)
        self.label_Main_bg.setObjectName("label_Main_bg")


        self.label_recog = QtWidgets.QLabel(self.centralwidget)
        self.label_recog.setGeometry(QtCore.QRect(430, 390, 461, 141))
        self.label_recog.setText("")
        self.label_recog.setPixmap(QtGui.QPixmap("../guiobject/recognize.gif"))
        self.label_recog.setScaledContents(True)
        self.label_recog.setObjectName("label_recog")


        self.label_start = QtWidgets.QLabel(self.centralwidget)
        self.label_start.setGeometry(QtCore.QRect(370, 610, 221, 81))
        self.label_start.setText("")
        self.label_start.setPixmap(QtGui.QPixmap("../guiobject/Start.png"))
        self.label_start.setScaledContents(True)
        self.label_start.setObjectName("label_start")


        self.label_quite = QtWidgets.QLabel(self.centralwidget)
        self.label_quite.setGeometry(QtCore.QRect(720, 620, 221, 71))
        self.label_quite.setText("")
        self.label_quite.setPixmap(QtGui.QPixmap("../guiobject/Quit.png"))
        self.label_quite.setScaledContents(True)
        self.label_quite.setObjectName("label_quite")


        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(380, 630, 191, 51))
        self.start.setText("")
        self.start.setObjectName("start")


        self.quite = QtWidgets.QPushButton(self.centralwidget)
        self.quite.setGeometry(QtCore.QRect(730, 630, 191, 51))
        self.quite.setText("")
        self.quite.setObjectName("quite")


        self.label_tb1 = QtWidgets.QLabel(self.centralwidget)
        self.label_tb1.setGeometry(QtCore.QRect(0, 0, 301, 151))
        self.label_tb1.setText("")
        self.label_tb1.setPixmap(QtGui.QPixmap("../guiobject/textBg.jpg"))
        self.label_tb1.setScaledContents(True)
        self.label_tb1.setObjectName("label_tb1")


        self.label_tb2 = QtWidgets.QLabel(self.centralwidget)
        self.label_tb2.setGeometry(QtCore.QRect(1000, 0, 301, 151))
        self.label_tb2.setText("")
        self.label_tb2.setPixmap(QtGui.QPixmap("../guiobject/textBg.jpg"))
        self.label_tb2.setScaledContents(True)
        self.label_tb2.setObjectName("label_tb2")


        self.label_tb3 = QtWidgets.QLabel(self.centralwidget)
        self.label_tb3.setGeometry(QtCore.QRect(0, 600, 301, 151))
        self.label_tb3.setText("")
        self.label_tb3.setPixmap(QtGui.QPixmap("../guiobject/textBg.jpg"))
        self.label_tb3.setScaledContents(True)
        self.label_tb3.setObjectName("label_tb3")


        self.label_tb4 = QtWidgets.QLabel(self.centralwidget)
        self.label_tb4.setGeometry(QtCore.QRect(1010, 600, 301, 151))
        self.label_tb4.setText("")
        self.label_tb4.setPixmap(QtGui.QPixmap("../guiobject/textBg.jpg"))
        self.label_tb4.setScaledContents(True)
        self.label_tb4.setObjectName("label_tb4")


        self.MainMsgBox = QtWidgets.QLabel(self.centralwidget)
        self.MainMsgBox.setGeometry(QtCore.QRect(280, 30, 741, 311))
        self.MainMsgBox.setText("")
        self.MainMsgBox.setPixmap(QtGui.QPixmap("../guiobject/textBg2.jpg"))
        self.MainMsgBox.setScaledContents(True)
        self.MainMsgBox.setObjectName("MainMsgBox")


        self.label_earth = QtWidgets.QLabel(self.centralwidget)
        self.label_earth.setGeometry(QtCore.QRect(-20, 290, 301, 211))
        self.label_earth.setText("")
        self.label_earth.setPixmap(QtGui.QPixmap("../guiobject/Earth.gif"))
        self.label_earth.setScaledContents(True)
        self.label_earth.setObjectName("label_earth")


        self.lable_init = QtWidgets.QLabel(self.centralwidget)
        self.lable_init.setGeometry(QtCore.QRect(1030, 270, 281, 251))
        self.lable_init.setText("")
        self.lable_init.setPixmap(QtGui.QPixmap("../guiobject/initiate.gif"))
        self.lable_init.setScaledContents(True)
        self.lable_init.setObjectName("lable_init")


        self.tb1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb1.setGeometry(QtCore.QRect(30, 30, 231, 91))
        self.tb1.setStyleSheet("border:none;\n"
"background:transparent;"
"font-size:25px;\n"
"color:white;"
)
        self.tb1.setObjectName("tb1")


        self.tb2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb2.setGeometry(QtCore.QRect(1030, 40, 231, 81))
        self.tb2.setStyleSheet("border:none;\n"
"background:transparent;"
"font-size:25px;\n"
"color:white;"
)
        self.tb2.setObjectName("tb2")


        self.tb3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb3.setGeometry(QtCore.QRect(30, 640, 231, 81))
        self.tb3.setStyleSheet("border:none;\n"
"background:transparent;"
"font-size:25px;\n"
"color:white;"
)
        self.tb3.setObjectName("tb3")


        self.tb4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb4.setGeometry(QtCore.QRect(1040, 640, 231, 81))
        self.tb4.setStyleSheet("border:none;\n"
"background:transparent;")
        self.tb4.setObjectName("tb4")


        self.MainMsg_tb = QtWidgets.QTextBrowser(self.centralwidget)
        self.MainMsg_tb.setGeometry(QtCore.QRect(400, 100, 501, 171))
        self.MainMsg_tb.setStyleSheet("border:none;\n"
"background:transparent;"
"font-size:20px;\n"
"color:white;\n"
"scroll-behaviour:auto;"
)
        self.MainMsg_tb.setObjectName("MainMsg_tb")


        self.label_textRecog = QtWidgets.QLabel(self.centralwidget)
        self.label_textRecog.setGeometry(QtCore.QRect(370, 350, 581, 231))
        self.label_textRecog.setText("")
        self.label_textRecog.setPixmap(QtGui.QPixmap("../guiobject/textGif.gif"))
        self.label_textRecog.setScaledContents(True)
        self.label_textRecog.setObjectName("label_textRecog")


        self.label_Main_bg.raise_()
        self.label_textRecog.raise_()
        self.label_recog.raise_()
        self.label_start.raise_()
        self.label_quite.raise_()
        self.start.raise_()
        self.quite.raise_()
        self.label_tb1.raise_()
        self.label_tb2.raise_()
        self.label_tb3.raise_()
        self.label_tb4.raise_()
        self.MainMsgBox.raise_()
        self.label_earth.raise_()
        self.lable_init.raise_()
        self.tb1.raise_()
        self.tb2.raise_()
        self.tb3.raise_()
        self.tb4.raise_()
        self.MainMsg_tb.raise_()


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1308, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Ronny The Voice Assistent", "Ronny The Voice Assistent"))

        #ronny.wishme()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

